### PR TITLE
Support for the CRM imports API

### PR DESCRIPTION
**Pull request by sblackstone**
This patch adds support for the v3.0 crm/imports endpoint.

https://developers.hubspot.com/docs/api/crm/imports

### Notes

- Modified hubspot.go to add support for multipart mime which included abstracting out the content-type and detecting when to not call JSON.marshal on the input (since we're dealing with mime multipart here). I'm open to other ways to handle this, but this seems as clean as possible without doing some more major refactoring...

- All of these APIs return huge structures of data that I don't think is worth trying to unmarshall into a struct - so I've left all the return values as map[string]interface{}.   This also future proofs us as these fields could easily change based on Hubspot's implementation.

- Data for CSV/Spreadsheets is represented as an `io.Reader` passed into the CrmImportConfig - this allows us to accept data from files, buffers, etc.

- I've written a test file `crm_imports_test.go` which includes examples for each of these functions but doesn't actually assert anything - I'm not sure how you'd like to proceed with that since 1) these are hard to test and 2) any tests require a hubspot account to test against.

- The `Start` function  has been placed into it's own file due to its complexity - the rest of this patch should follow the conventions of this codebase.

Thanks,
Stephen

An example, to start an import:

```go
&CrmImportConfig{
		Name: "Example Create Import",
		ImportOperations: map[string]string{
			"0-1": "CREATE",
		},
		Files: []CrmImportFileConfig{
			{
				FileName:   "example.csv",
				FileFormat: "CSV",
				DateFormat: "DAY_MONTH_YEAR",
				Data:       createTestCsv(6), // This fn returns io.Reader of a CSV example...
				FileImportPage: CrmImportFilePageConfig{
					HasHeader: true,
					ColumnMappings: []CrmImportColumnMapping{
						{
							ColumnObjectTypeId: "0-1",
							ColumnName:         "email",
							PropertyName:       "email",
							IdColumnType:       "HUBSPOT_ALTERNATE_ID",
						},
						{
							ColumnObjectTypeId: "0-1",
							ColumnName:         "firstname",
							PropertyName:       "firstname",
						},
						{
							ColumnObjectTypeId: "0-1",
							ColumnName:         "lastname",
							PropertyName:       "lastname",
						},
					},
				},
			},
		},
	}
```

### CODE REVIEW

**Comment by sblackstone** [comment]
Added two small cleanups today:

Renamed FileImportPageConfig -> CrmImportFilePageConfig so its consitent.

Renamed "js" variable in `gohubspot.go` to requestBody since it's not necessarily json anymore...

**Comment by kk-no** [comment]
Thank you for your PR.
The review is expected to take some time.

As a supplement, you can apply automatic formatting with `make fmt`, so please try using it.

**Comment by sblackstone** [comment]
> Thank you for your PR. The review is expected to take some time.
> 
> As a supplement, you can apply automatic formatting with `make fmt`, so please try using it.

No prob.  I pushed a `make fmt` fix which only removed one extra blank line...

**Comment by sblackstone** [comment]
Hi there..

Any feedback on this?

Thanks!
Stephen

**Comment by kk-no** [comment]
@sblackstone 
Sorry for the delay.
I was thinking of a good abstraction around MIME Type, but couldn't come up with a good idea.
As for the pull request, it is LGTM, but I may change the base for NewRequest, CreateAndDo, etc. in a future version.

Please let me know if you have any concerns about using them. Thanks again!

**Review by kk-no — APPROVED** [review]

**Comment by sblackstone** [comment]
Thanks!

**Pull request merged**
